---
- name: Create user group
  group:
    name: "{{ ansible_arch_user.group }}"
    state: present
  tags:
    - user

- name: Create user and assign to group
  user:
    name: "{{ ansible_arch_user.name }}"
    group: "{{ ansible_arch_user.group }}"
    password: "{{ ansible_arch_user.password|password_hash('sha512') }}"
    shell: "{{ ansible_arch_user.shell }}"
    update_password: on_create
    groups: "{{ ansible_arch_user.groups }}"
    append: yes
  tags:
    - user
